### ISSUE TITLE
Test #2

### ISSUE THREAD

**Issue by uschtwill** [uschtwill/rails_jobboard#2]
This is a test issue...

**Comment by alvinkatojr** [comment]
Got it @uschtwill  :) +1:

**Comment by uschtwill** [comment]
Ah, but I have to to use the '@', so you'll get a notification, eh? @alvinkatojr

**Comment by alvinkatojr** [comment]
Yes you do @uschtwill :) It comes directly to me when you do that. I hope you are seeing how fun coding can be with tools like this :)

**Comment by uschtwill** [comment]
Haha, yeah. This is awesome... and SO convenient. I think you guys should have introduced us to this earlier. This is so much better than that stupid Google Moderator, and its even better than e-mail. How cool is it, when you request help and ask a question basically from within your code? This is neat! @alvinkatojr
